### ISSUE TITLE
CSSNext is a dangerous default that breaks core CSS functionality

### ISSUE THREAD

**Issue by mirisuzanne** [nuxt-community/starter-template#76]
### Version

[v1.4.0](https://github.com/starter-template/releases/tag/v1.4.0)

### Reproduction link

[https://github.com/mirisuzanne/no-cssnext/blob/master/pages/index.vue](https://github.com/mirisuzanne/no-cssnext/blob/master/pages/index.vue)

### Steps to reproduce

- download and run the dev server
- look at the output index.html in your browser

### What is expected ?

- the component background color should be red
- the CSS should have:

```scss
main { background-color: var(--bg, initial); }
```

### What is actually happening?

- the component background color is set to `initial`
- the CSS has no variables

```scss
main { background-color: transparent; background-color: initial; }
```

### Additional comments?

The gray bits display the output CSS so it is easy to find without digging. Even the cssnext repo (https://github.com/MoOx/postcss-cssnext) states that it's been deprecated in favor of https://preset-env.cssdb.org/

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/starter-template/issues/c55">#c55</a>)</em></sub></div>
